export const SELECT_SUBREDDITD = 'SELECT_SUBREDDITD';
export const INVALIDATE_SUBREDDITD = 'INVALIDATE_SUBREDDITD';
export const REQUEST_POSTD = 'REQUEST_POSTD';
export const RECEIVE_POSTD = 'RECEIVE_POSTD';